[package]
name = "ks_rs"
version = "0.1.0"
authors = ["Matthew Russell <matthewjohnrussell@gmail.com>"]
edition = "2018"

[dependencies]
ndarray = { version = "0.12.1", features = ["blas"] }
blas-src = { version = "0.2", default-features = false, features = ["openblas"] }
openblas-src = { version = "0.6", default-features = false, features = ["cblas", "static"] }
structopt = "0.3"
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
doctest = false

[[bin]]
name = "one_dim"
path = "src/bin/one_dim.rs"
test = false
doctest = false

[[bin]]
name = "one_dim_general"
path = "src/bin/one_dim_general.rs"
test = false
doctest = false

[[bin]]
name = "one_dim_chemotaxis"
path = "src/bin/one_dim_chemotaxis.rs"
test = false
doctest = false

[[bin]]
name = "one_dim_chemotaxis_7_var"
path = "src/bin/one_dim_chemotaxis_7_var.rs"
test = false
doctest = false

[[bin]]
name = "one_dim_diffusion_dirichlet"
path = "src/bin/one_dim_diffusion_dirichlet.rs"
test = false
doctest = false

[[bin]]
name = "two_dim"
path = "src/bin/two_dim.rs"
test = false
doctest = false

[dev-dependencies]
approx = "0.3.2"
