[package]
name = "ks_rs"
version = "0.1.0"
authors = ["Matthew Russell <matthewjohnrussell@gmail.com>"]
edition = "2018"

[dependencies]
ndarray = { version = "0.12.1", features = ["blas"] }
blas-src = { version = "0.2", default-features = false, features = ["openblas"] }
openblas-src = { version = "0.6", default-features = false, features = ["cblas", "static"] }
structopt = "0.2"
rand = "0.6.5"
# manually downgrade from 1.0.5 to work around RLS bug until it's fixed
bitflags = "=1.0.4"
